[package]
name = "dollfish"
version = "0.1.0"
edition = "2021"

[dependencies]
base64ct = "1.6.0"
reqwest = { version = "0.12.2", features = ["json"] }
serde = { version = "1.0.197", features = ["derive"] }
sha1 = "0.10.6"
tokio = { version = "1.37.0", features = ["full"] }

