# This will create a Jellyfin instance running inside docker for easy testing

services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Oslo
    volumes:
      - ./jellyfin/config:/config
      - ./jellyfin/tvshows:/data/tvshows
      - ./jellyfin/movies:/data/movies
    ports:
      - 8096:8096
    restart: unless-stopped

networks:
  default:
    name: jellyfin
