use serde::{Deserialize, Serialize};

#[derive(Serialize, Deserialize)]
pub struct Configuration {
    pub audio_language_preference: String,
    pub cast_receiver_id: String,
    pub display_collections_view: bool,
    pub display_missing_episodes: bool,
    pub enable_local_password: bool,
    pub enable_next_episode_auto_play: bool,
    pub grouped_folders: Vec<String>,
    pub hide_played_in_latest: bool,
    pub latest_items_excludes: Vec<String>,
    pub my_media_excludeses: Vec<String>,
    pub ordered_views: Vec<String>,
    pub play_default_audio_track: bool,
    pub remember_audio_selections: bool,
    pub remember_subtitle_selections: bool,
    pub subtitle_language_preference: String,
    pub subtitle_mode: String,
}

#[derive(Serialize, Deserialize)]
pub struct Policy {
    pub access_schedules: Vec<AccessSchedules>,
    pub allowed_tags: Vec<String>,
    pub authentication_provider_id: String,
    pub block_unrated_items: Vec<String>,
    pub blocked_channels: Vec<String>,
    pub blocked_media_folders: Vec<String>,
    pub blocked_tags: Vec<String>,
    pub enable_all_channels: bool,
    pub enable_all_devices: bool,
    pub enable_all_folders: bool,
    pub enable_audio_playback_transcoding: bool,
    pub enable_collection_management: bool,
    pub enable_content_deletion: bool,
    pub enable_content_deletion_from_folders: Vec<String>,
    pub enable_content_downloading: bool,
    pub enable_live_tv_access: bool,
    pub enable_live_tv_management: bool,
    pub enable_lyric_management: bool,
    pub enable_media_conversion: bool,
    pub enable_media_playback: bool,
    pub enable_playback_remuxing: bool,
    pub enable_public_sharing: bool,
    pub enable_remote_access: bool,
    pub enable_remote_control_of_other_users: bool,
    pub enable_shared_device_control: bool,
    pub enable_subtitle_management: bool,
    pub enable_sync_transcoding: bool,
    pub enable_user_preference_access: bool,
    pub enable_video_playback_transcoding: bool,
    pub enabled_channels: Vec<String>,
    pub enabled_devices: Vec<String>,
    pub enabled_folders: Vec<String>,
    pub force_remote_source_transcoding: bool,
    pub invalid_login_attempt_count: i32,
    pub is_administrator: bool,
    pub is_disabled: bool,
    pub is_hidden: bool,
    pub login_attempts_before_lockout: i32,
    pub max_actie_sessions: i32,
    pub max_parental_rating: i32,
    pub password_reset_provider_id: String,
    pub remote_client_bitrate_limit: i32,
    pub sync_play_access: String,
}

#[derive(Serialize, Deserialize)]
pub struct AccessSchedules {
    pub day_of_week: String,
    pub end_hour: i32,
    pub id: i32,
    pub start_hour: i32,
    pub user_id: String,
}
